version: '3'
services:
  udagram-db:i
    image: postgres:latest
    container_name: udagram-db
    environment:
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_USER: "$POSTGRES_USER"
      POSTGRES_DB: "$POSTGRES_DB"
    networks:
      - udagram

  backend_user:
    image: udagram-api-user
    container_name: udagram-backend-user
    environment:
      POSTGRES_USERNAME: "$POSTRGRES_USERNAME"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: "$POSTGRES_DB"
      POSTGRES_HOST: "$POSTGRES_HOST"
      AWS_REGION: "$AWS_REGION"
      AWS_PROFILE: "$AWS_PROFILE"
      AWS_BUCKET: "$AWS_BUCKET"
      JWT_SECRET: "$JWT_SECRET"
      URL: http://udagram-frontend:8100
    depends_on:
      - udagram-db
    networks:
      - udagram

  backend_feed:
    image: udagram-api-feed
    container_name: udagram-backend-feed
    environment:
      POSTGRES_USERNAME: "$POSTGRES_USERNAME"
      POSTGRES_PASSWORD: "$POSTGRES_PASSWORD"
      POSTGRES_DB: "$POSTGRES_DB"
      POSTGRES_HOST: "$POSTGRES_HOST"
      AWS_REGION: "$AWS_REGION"
      AWS_PROFILE: "$AWS_PROFILE"
      AWS_BUCKET: "$AWS_BUCKET"
      JWT_SECRET:  "$JWT_SECRET"
      URL: http://udagram-frontend:8100
    depends_on:
      - udagram-db
    networks:
      - udagram

  frontend:
    image: pasciano007/udagram-frontend
    container_name: udagram-frontend
    ports:
      - "8100:80"
    networks:
      - udagram

  reverseproxy:
    image: reverseproxy
    container_name: udagram-reverseproxy
    ports:
      - "8080:8080"
    depends_on:
      - backend_user
      - backend_feed
      - udagram-db
    networks:
      - udagram

networks:
  udagramnetwork:

